
#
# This is the user-interface definition of a Shiny web application. You can
# run the application by clicking 'Run App' above.
#
# Find out more about building applications with Shiny here:
#
#    http://shiny.rstudio.com/
#

# Define UI for application

######################## Imagem inicial ############################

shinyUI(fluidPage(
  navbarPage(title="Brasileirão 2003-2020", theme = shinytheme("flatly"),
             tabPanel("Inicio",
                      #tabsetPanel(
                      #tabPanel(" ",
                      fluidRow(
                        column(12,
                               img(src = "Brasileirao.jpg", height = 680, width = 1550)#DT::dataTableOutput("table1")
                        ))#)
                      ##
                      
                      
                      
                      #)# barra de navegacao interna
             ),# barra de navegacao superior (d2021 do Participante)
             
             ####################### ABA Tabela ############################
             
             tabPanel("Tabela Brasileirão",
                      tabsetPanel(
                        tabPanel("Jogos do Brasileirão 2003-2020",
                                 fluidRow(
                                   column(12,
                                          DT::dataTableOutput("table1")
                                   ))),
                        #
                        
                        
                        tabPanel("Confrontos",
                                 fluidRow(column(3, 
                                                 selectInput("TIME123", 
                                                             strong("Selecione o Mandante:"), 
                                                             choices=c("AMERICA-MG",
                                                                       "AMERICA-RN",
                                                                       "ATHLETICO-PR",
                                                                       "ATLETICO-GO",
                                                                       "ATLETICO-MG",
                                                                       "AVAI",
                                                                       "BAHIA",
                                                                       "BARUERI",
                                                                       "BOTAFOGO-RJ",
                                                                       "BRAGANTINO",
                                                                       "BRASILIENSE",
                                                                       "CEARA",
                                                                       "CHAPECOENSE",
                                                                       "CORINTHIANS",
                                                                       "CORITIBA",
                                                                       "CRICIUMA",
                                                                       "CRUZEIRO",
                                                                       "CSA",
                                                                       "FIGUEIRENSE",
                                                                       "FLAMENGO",
                                                                       "FLUMINENSE",
                                                                       "FORTALEZA",
                                                                       "GOIAS",
                                                                       "GREMIO",
                                                                       "GREMIO PRUDENTE",
                                                                       "GUARANI",
                                                                       "INTERNACIONAL",
                                                                       "IPATINGA",
                                                                       "JOINVILLE",
                                                                       "JUVENTUDE",
                                                                       "NAUTICO",
                                                                       "PALMEIRAS",
                                                                       "PARANA",
                                                                       "PAYSANDU",
                                                                       "PONTE PRETA",
                                                                       "PORTUGUESA",
                                                                       "SANTA CRUZ",
                                                                       "SANTO ANDRE",
                                                                       "SANTOS",
                                                                       "SAO CAETANO",
                                                                       "SAO PAULO",
                                                                       "SPORT",
                                                                       "VASCO",
                                                                       "VITORIA"
                                                                       
                                                             ),
                                                             selected = "FLAMENGO"),
                                                 
                                                 selectInput("TIME124", 
                                                             strong("Selecione o Visitante:"), 
                                                             choices=c(
                                                               "AMERICA-MG",
                                                               "AMERICA-RN",
                                                               "ATHLETICO-PR",
                                                               "ATLETICO-GO",
                                                               "ATLETICO-MG",
                                                               "AVAI",
                                                               "BAHIA",
                                                               "BARUERI",
                                                               "BOTAFOGO-RJ",
                                                               "BRAGANTINO",
                                                               "BRASILIENSE",
                                                               "CEARA",
                                                               "CHAPECOENSE",
                                                               "CORINTHIANS",
                                                               "CORITIBA",
                                                               "CRICIUMA",
                                                               "CRUZEIRO",
                                                               "CSA",
                                                               "FIGUEIRENSE",
                                                               "FLAMENGO",
                                                               "FLUMINENSE",
                                                               "FORTALEZA",
                                                               "GOIAS",
                                                               "GREMIO",
                                                               "GREMIO PRUDENTE",
                                                               "GUARANI",
                                                               "INTERNACIONAL",
                                                               "IPATINGA",
                                                               "JOINVILLE",
                                                               "JUVENTUDE",
                                                               "NAUTICO",
                                                               "PALMEIRAS",
                                                               "PARANA",
                                                               "PAYSANDU",
                                                               "PONTE PRETA",
                                                               "PORTUGUESA",
                                                               "SANTA CRUZ",
                                                               "SANTO ANDRE",
                                                               "SANTOS",
                                                               "SAO CAETANO",
                                                               "SAO PAULO",
                                                               "SPORT",
                                                               "VASCO",
                                                               "VITORIA"
                                                             ),
                                                             selected = "SAO PAULO")),
                                          column(9, DT::dataTableOutput("tab122"))))
                        
                        ##
                        
                        
                        
                      )# barra de navegacao interna
             ),# barra de navegacao superior (d2021 do Participante)
             
             ####################### ABA ARENA ############################
             
             tabPanel("Arenas",
                      tabsetPanel(
                        ##
                        tabPanel("Jogos por Arena",
                                 fluidRow(column(3, 
                                                 selectInput("Temporada1", 
                                                             strong("Selecione o Ano:"), 
                                                             choices=c("2003"="2003",
                                                                       "2004"="2004",
                                                                       "2005"="2005",
                                                                       "2006"="2006",
                                                                       "2007"="2007",
                                                                       "2008"="2008",
                                                                       "2009"="2009",
                                                                       "2010"="2010",
                                                                       "2011"="2011",
                                                                       "2012"="2012",
                                                                       "2013"="2013",
                                                                       "2014"="2014",
                                                                       "2015"="2015",
                                                                       "2016"="2016",
                                                                       "2017"="2017",
                                                                       "2018"="2018",
                                                                       "2019"="2019",
                                                                       "2020"="2020"),
                                                             selected = "2020")),
                                          column(9,
                                                 plotlyOutput("plot21", height = 600)))),
                        
                        tabPanel("Arenas com mais jogos",
                                 fluidRow(column(9,
                                                 plotlyOutput("plot1", height = 600)))),
                        tabPanel("Arenas com menos jogos",
                                 fluidRow(column(9,
                                                 plotlyOutput("plot2", height = 600))))
                        
                      )# barra de navegacao interna
             ),# barra de navegacao superior (d2021 da Escola)
             
             ######################## ABA PONTOS ############################
             
             tabPanel("Pontuação",
                      tabsetPanel(
                        ##
                        tabPanel("Pontuação final",
                                 fluidRow(column(3, 
                                                 selectInput("Temporada53", 
                                                             strong("Selecione o Ano:"), 
                                                             choices=c("Todas Temporada"= "Todas Temporada",
                                                                       "2003"="2003",
                                                                       "2004"="2004",
                                                                       "2005"="2005",
                                                                       "2006"="2006",
                                                                       "2007"="2007",
                                                                       "2008"="2008",
                                                                       "2009"="2009",
                                                                       "2010"="2010",
                                                                       "2011"="2011",
                                                                       "2012"="2012",
                                                                       "2013"="2013",
                                                                       "2014"="2014",
                                                                       "2015"="2015",
                                                                       "2016"="2016",
                                                                       "2017"="2017",
                                                                       "2018"="2018",
                                                                       "2019"="2019",
                                                                       "2020"="2020"),
                                                             selected = "2020")),
                                          column(9,
                                                 plotlyOutput("plot5", height = 600),
                                                 tableOutput("tabTemporada53")))),
                        tabPanel("Pontuação como Mandante",
                                 fluidRow(column(3, 
                                                 selectInput("Temporada51", 
                                                             strong("Selecione o Ano:"), 
                                                             choices=c("Todas Temporada"= "Todas Temporada",
                                                                       "2003"="2003",
                                                                       "2004"="2004",
                                                                       "2005"="2005",
                                                                       "2006"="2006",
                                                                       "2007"="2007",
                                                                       "2008"="2008",
                                                                       "2009"="2009",
                                                                       "2010"="2010",
                                                                       "2011"="2011",
                                                                       "2012"="2012",
                                                                       "2013"="2013",
                                                                       "2014"="2014",
                                                                       "2015"="2015",
                                                                       "2016"="2016",
                                                                       "2017"="2017",
                                                                       "2018"="2018",
                                                                       "2019"="2019",
                                                                       "2020"="2020"),
                                                             selected = "2020")),
                                          column(9,
                                                 plotlyOutput("plot3", height = 600)))),
                        
                        tabPanel("Pontuação como Visitante",
                                 fluidRow(column(3, 
                                                 selectInput("Temporada52", 
                                                             strong("Selecione o Ano:"), 
                                                             choices=c("Todas Temporada"= "Todas Temporada",
                                                                       "2003"="2003",
                                                                       "2004"="2004",
                                                                       "2005"="2005",
                                                                       "2006"="2006",
                                                                       "2007"="2007",
                                                                       "2008"="2008",
                                                                       "2009"="2009",
                                                                       "2010"="2010",
                                                                       "2011"="2011",
                                                                       "2012"="2012",
                                                                       "2013"="2013",
                                                                       "2014"="2014",
                                                                       "2015"="2015",
                                                                       "2016"="2016",
                                                                       "2017"="2017",
                                                                       "2018"="2018",
                                                                       "2019"="2019",
                                                                       "2020"="2020"),
                                                             selected = "2020")),
                                          column(9,
                                                 plotlyOutput("plot4", height = 600)))),
                        tabPanel("Maior pontuação",
                                 fluidRow(column(3, 
                                                 selectInput("Temporada99", 
                                                             strong("Selecione o Ano:"), 
                                                             choices=c("2003"="2003",
                                                                       "2004"="2004",
                                                                       "2005"="2005",
                                                                       "2006"="2006",
                                                                       "2007"="2007",
                                                                       "2008"="2008",
                                                                       "2009"="2009",
                                                                       "2010"="2010",
                                                                       "2011"="2011",
                                                                       "2012"="2012",
                                                                       "2013"="2013",
                                                                       "2014"="2014",
                                                                       "2015"="2015",
                                                                       "2016"="2016",
                                                                       "2017"="2017",
                                                                       "2018"="2018",
                                                                       "2019"="2019",
                                                                       "2020"="2020"),
                                                             selected = "2020")),
                                          column(9,
                                                 plotlyOutput("plot99", height = 600)))),
                        tabPanel("Menor Pontuação",
                                 fluidRow(column(3, 
                                                 selectInput("Temporada98", 
                                                             strong("Selecione o Ano:"), 
                                                             choices=c("2003"="2003",
                                                                       "2004"="2004",
                                                                       "2005"="2005",
                                                                       "2006"="2006",
                                                                       "2007"="2007",
                                                                       "2008"="2008",
                                                                       "2009"="2009",
                                                                       "2010"="2010",
                                                                       "2011"="2011",
                                                                       "2012"="2012",
                                                                       "2013"="2013",
                                                                       "2014"="2014",
                                                                       "2015"="2015",
                                                                       "2016"="2016",
                                                                       "2017"="2017",
                                                                       "2018"="2018",
                                                                       "2019"="2019",
                                                                       "2020"="2020"),
                                                             selected = "2020")),
                                          column(9,
                                                 plotlyOutput("plot98", height = 600))))
                        
                      )# barra de navegacao interna
             ),# barra de navegacao superior (d2021 da Escola)  
             
             ######################## ABA VITORIAS ############################
             
             tabPanel("Vitórias",
                      tabsetPanel(
                        ##
                        tabPanel("Vitórias por Temporada",
                                 fluidRow(column(3, 
                                                 selectInput("Temporada2", 
                                                             strong("Selecione o Ano:"), 
                                                             choices=c("Todas Temporada"= "Todas Temporada",
                                                                       "2003"="2003",
                                                                       "2004"="2004",
                                                                       "2005"="2005",
                                                                       "2006"="2006",
                                                                       "2007"="2007",
                                                                       "2008"="2008",
                                                                       "2009"="2009",
                                                                       "2010"="2010",
                                                                       "2011"="2011",
                                                                       "2012"="2012",
                                                                       "2013"="2013",
                                                                       "2014"="2014",
                                                                       "2015"="2015",
                                                                       "2016"="2016",
                                                                       "2017"="2017",
                                                                       "2018"="2018",
                                                                       "2019"="2019",
                                                                       "2020"="2020"),
                                                             selected = "2020")),
                                          column(9,
                                                 plotlyOutput("plot22", height = 600)))),
                        tabPanel("Vitórias como Mandante",
                                 fluidRow(column(3, 
                                                 selectInput("Temporada22", 
                                                             strong("Selecione o Ano:"), 
                                                             choices=c("Todas Temporada"= "Todas Temporada",
                                                                       "2003"="2003",
                                                                       "2004"="2004",
                                                                       "2005"="2005",
                                                                       "2006"="2006",
                                                                       "2007"="2007",
                                                                       "2008"="2008",
                                                                       "2009"="2009",
                                                                       "2010"="2010",
                                                                       "2011"="2011",
                                                                       "2012"="2012",
                                                                       "2013"="2013",
                                                                       "2014"="2014",
                                                                       "2015"="2015",
                                                                       "2016"="2016",
                                                                       "2017"="2017",
                                                                       "2018"="2018",
                                                                       "2019"="2019",
                                                                       "2020"="2020"),
                                                             selected = "2020")),
                                          column(9,
                                                 plotlyOutput("plot6", height = 600)))),
                        
                        tabPanel("Vitórias como Visitante",
                                 fluidRow(column(3, 
                                                 selectInput("Temporada42", 
                                                             strong("Selecione o Ano:"), 
                                                             choices=c("Todas Temporada"= "Todas Temporada",
                                                                       "2003"="2003",
                                                                       "2004"="2004",
                                                                       "2005"="2005",
                                                                       "2006"="2006",
                                                                       "2007"="2007",
                                                                       "2008"="2008",
                                                                       "2009"="2009",
                                                                       "2010"="2010",
                                                                       "2011"="2011",
                                                                       "2012"="2012",
                                                                       "2013"="2013",
                                                                       "2014"="2014",
                                                                       "2015"="2015",
                                                                       "2016"="2016",
                                                                       "2017"="2017",
                                                                       "2018"="2018",
                                                                       "2019"="2019",
                                                                       "2020"="2020"),
                                                             selected = "2020")),
                                          column(9,
                                                 plotlyOutput("plot7", height = 600))))
                        
                        
                      )# barra de navegacao interna
             ),# barra de navegacao superior (d2021 da Escola)  
             
             ######################## ABA EMPATES ############################
             
             tabPanel("Empates",
                      tabsetPanel(
                        ##
                        tabPanel("Empates por Temporada",
                                 fluidRow(column(3, 
                                                 selectInput("Temporada91", 
                                                             strong("Selecione o Ano:"), 
                                                             choices=c("Todas Temporada"= "Todas Temporada",
                                                                       "2003"="2003",
                                                                       "2004"="2004",
                                                                       "2005"="2005",
                                                                       "2006"="2006",
                                                                       "2007"="2007",
                                                                       "2008"="2008",
                                                                       "2009"="2009",
                                                                       "2010"="2010",
                                                                       "2011"="2011",
                                                                       "2012"="2012",
                                                                       "2013"="2013",
                                                                       "2014"="2014",
                                                                       "2015"="2015",
                                                                       "2016"="2016",
                                                                       "2017"="2017",
                                                                       "2018"="2018",
                                                                       "2019"="2019",
                                                                       "2020"="2020"),
                                                             selected = "2020")),
                                          column(9,
                                                 plotlyOutput("plot9", height = 600)))),
                        tabPanel("Empates como Mandante",
                                 fluidRow(column(3, 
                                                 selectInput("Temporada92", 
                                                             strong("Selecione o Ano:"), 
                                                             choices=c("Todas Temporada"= "Todas Temporada",
                                                                       "2003"="2003",
                                                                       "2004"="2004",
                                                                       "2005"="2005",
                                                                       "2006"="2006",
                                                                       "2007"="2007",
                                                                       "2008"="2008",
                                                                       "2009"="2009",
                                                                       "2010"="2010",
                                                                       "2011"="2011",
                                                                       "2012"="2012",
                                                                       "2013"="2013",
                                                                       "2014"="2014",
                                                                       "2015"="2015",
                                                                       "2016"="2016",
                                                                       "2017"="2017",
                                                                       "2018"="2018",
                                                                       "2019"="2019",
                                                                       "2020"="2020"),
                                                             selected = "2020")),
                                          column(9,
                                                 plotlyOutput("plot10", height = 600)))),
                        tabPanel("Empates como Visitante",
                                 fluidRow(column(3, 
                                                 selectInput("Temporada93", 
                                                             strong("Selecione o Ano:"), 
                                                             choices=c("Todas Temporada"= "Todas Temporada",
                                                                       "2003"="2003",
                                                                       "2004"="2004",
                                                                       "2005"="2005",
                                                                       "2006"="2006",
                                                                       "2007"="2007",
                                                                       "2008"="2008",
                                                                       "2009"="2009",
                                                                       "2010"="2010",
                                                                       "2011"="2011",
                                                                       "2012"="2012",
                                                                       "2013"="2013",
                                                                       "2014"="2014",
                                                                       "2015"="2015",
                                                                       "2016"="2016",
                                                                       "2017"="2017",
                                                                       "2018"="2018",
                                                                       "2019"="2019",
                                                                       "2020"="2020"),
                                                             selected = "2020")),
                                          column(9,
                                                 plotlyOutput("plot11", height = 600))))
                        
                        
                      )# barra de navegacao interna
             ),# barra de navegacao superior (d2021 da Escola)  
             
             ######################## ABA DERROTAS ############################
             
             tabPanel("Derrotas",
                      tabsetPanel(
                        ##
                        tabPanel("Derrotas por Temporada",
                                 fluidRow(column(3, 
                                                 selectInput("Temporada3", 
                                                             strong("Selecione o Ano:"), 
                                                             choices=c("Todas Temporada"= "Todas Temporada",
                                                                       "2003"="2003",
                                                                       "2004"="2004",
                                                                       "2005"="2005",
                                                                       "2006"="2006",
                                                                       "2007"="2007",
                                                                       "2008"="2008",
                                                                       "2009"="2009",
                                                                       "2010"="2010",
                                                                       "2011"="2011",
                                                                       "2012"="2012",
                                                                       "2013"="2013",
                                                                       "2014"="2014",
                                                                       "2015"="2015",
                                                                       "2016"="2016",
                                                                       "2017"="2017",
                                                                       "2018"="2018",
                                                                       "2019"="2019",
                                                                       "2020"="2020"),
                                                             selected = "2020")),
                                          column(9,
                                                 plotlyOutput("plot23", height = 600)))),
                        tabPanel("Derrotas como Mandante",
                                 fluidRow(column(3,
                                                 selectInput("Temporada95", 
                                                             strong("Selecione o Ano:"), 
                                                             choices=c("Todas Temporada"= "Todas Temporada",
                                                                       "2003"="2003",
                                                                       "2004"="2004",
                                                                       "2005"="2005",
                                                                       "2006"="2006",
                                                                       "2007"="2007",
                                                                       "2008"="2008",
                                                                       "2009"="2009",
                                                                       "2010"="2010",
                                                                       "2011"="2011",
                                                                       "2012"="2012",
                                                                       "2013"="2013",
                                                                       "2014"="2014",
                                                                       "2015"="2015",
                                                                       "2016"="2016",
                                                                       "2017"="2017",
                                                                       "2018"="2018",
                                                                       "2019"="2019",
                                                                       "2020"="2020"),
                                                             selected = "2020")),
                                          column(9,
                                                 plotlyOutput("plot13", height = 600)))),
                        tabPanel("Derrotas como Visitante",
                                 fluidRow(column(3,
                                                 selectInput("Temporada94", 
                                                             strong("Selecione o Ano:"), 
                                                             choices=c("Todas Temporada"= "Todas Temporada",
                                                                       "2003"="2003",
                                                                       "2004"="2004",
                                                                       "2005"="2005",
                                                                       "2006"="2006",
                                                                       "2007"="2007",
                                                                       "2008"="2008",
                                                                       "2009"="2009",
                                                                       "2010"="2010",
                                                                       "2011"="2011",
                                                                       "2012"="2012",
                                                                       "2013"="2013",
                                                                       "2014"="2014",
                                                                       "2015"="2015",
                                                                       "2016"="2016",
                                                                       "2017"="2017",
                                                                       "2018"="2018",
                                                                       "2019"="2019",
                                                                       "2020"="2020"),
                                                             selected = "2020")),
                                          column(9,
                                                 plotlyOutput("plot14", height = 600))))
                        
                        
                      )# barra de navegacao interna
             ),# barra de navegacao superior (d2021 da Escola)  
             
             ######################## ABA GOLS ############################
             
             tabPanel("Gols por equipes",
                      tabsetPanel(
                        ##
                        tabPanel("Gols pró por Temporada",
                                 fluidRow(column(3, 
                                                 selectInput("Temporada59", 
                                                             strong("Selecione o Ano:"), 
                                                             choices=c("Todas Temporada"= "Todas Temporada",
                                                                       "2003"="2003",
                                                                       "2004"="2004",
                                                                       "2005"="2005",
                                                                       "2006"="2006",
                                                                       "2007"="2007",
                                                                       "2008"="2008",
                                                                       "2009"="2009",
                                                                       "2010"="2010",
                                                                       "2011"="2011",
                                                                       "2012"="2012",
                                                                       "2013"="2013",
                                                                       "2014"="2014",
                                                                       "2015"="2015",
                                                                       "2016"="2016",
                                                                       "2017"="2017",
                                                                       "2018"="2018",
                                                                       "2019"="2019",
                                                                       "2020"="2020"),
                                                             selected = "2020")),
                                          column(9,
                                                 plotlyOutput("plot59", height = 600)))),
                        tabPanel("Gols pró como Mandante",
                                 fluidRow(column(3, 
                                                 selectInput("Temporada84", 
                                                             strong("Selecione o Ano:"), 
                                                             choices=c("Todas Temporada"= "Todas Temporada",
                                                                       "2003"="2003",
                                                                       "2004"="2004",
                                                                       "2005"="2005",
                                                                       "2006"="2006",
                                                                       "2007"="2007",
                                                                       "2008"="2008",
                                                                       "2009"="2009",
                                                                       "2010"="2010",
                                                                       "2011"="2011",
                                                                       "2012"="2012",
                                                                       "2013"="2013",
                                                                       "2014"="2014",
                                                                       "2015"="2015",
                                                                       "2016"="2016",
                                                                       "2017"="2017",
                                                                       "2018"="2018",
                                                                       "2019"="2019",
                                                                       "2020"="2020"),
                                                             selected = "2020")),
                                          column(9,
                                                 plotlyOutput("plot16", height = 600)))),
                        tabPanel("Gols pró como Visitante",
                                 fluidRow(column(3, 
                                                 selectInput("Temporada85", 
                                                             strong("Selecione o Ano:"), 
                                                             choices=c("Todas Temporada"= "Todas Temporada",
                                                                       "2003"="2003",
                                                                       "2004"="2004",
                                                                       "2005"="2005",
                                                                       "2006"="2006",
                                                                       "2007"="2007",
                                                                       "2008"="2008",
                                                                       "2009"="2009",
                                                                       "2010"="2010",
                                                                       "2011"="2011",
                                                                       "2012"="2012",
                                                                       "2013"="2013",
                                                                       "2014"="2014",
                                                                       "2015"="2015",
                                                                       "2016"="2016",
                                                                       "2017"="2017",
                                                                       "2018"="2018",
                                                                       "2019"="2019",
                                                                       "2020"="2020"),
                                                             selected = "2020")),
                                          column(9,
                                                 plotlyOutput("plot17", height = 600)))),
                        tabPanel("Gols Sofridos por temporada",
                                 fluidRow(column(3, 
                                                 selectInput("Temporada302", 
                                                             strong("Selecione o Ano:"), 
                                                             choices=c("Todas Temporada"= "Todas Temporada",
                                                                       "2003"="2003",
                                                                       "2004"="2004",
                                                                       "2005"="2005",
                                                                       "2006"="2006",
                                                                       "2007"="2007",
                                                                       "2008"="2008",
                                                                       "2009"="2009",
                                                                       "2010"="2010",
                                                                       "2011"="2011",
                                                                       "2012"="2012",
                                                                       "2013"="2013",
                                                                       "2014"="2014",
                                                                       "2015"="2015",
                                                                       "2016"="2016",
                                                                       "2017"="2017",
                                                                       "2018"="2018",
                                                                       "2019"="2019",
                                                                       "2020"="2020"),
                                                             selected = "2020")),
                                          column(9,
                                                 plotlyOutput("plot302", height = 600)))),
                        tabPanel("Gols Sofridos como Mandante",
                                 fluidRow(column(3, 
                                                 selectInput("Temporada300", 
                                                             strong("Selecione o Ano:"), 
                                                             choices=c("Todas Temporada"= "Todas Temporada",
                                                                       "2003"="2003",
                                                                       "2004"="2004",
                                                                       "2005"="2005",
                                                                       "2006"="2006",
                                                                       "2007"="2007",
                                                                       "2008"="2008",
                                                                       "2009"="2009",
                                                                       "2010"="2010",
                                                                       "2011"="2011",
                                                                       "2012"="2012",
                                                                       "2013"="2013",
                                                                       "2014"="2014",
                                                                       "2015"="2015",
                                                                       "2016"="2016",
                                                                       "2017"="2017",
                                                                       "2018"="2018",
                                                                       "2019"="2019",
                                                                       "2020"="2020"),
                                                             selected = "2020")),
                                          column(9,
                                                 plotlyOutput("plot300", height = 600)))),
                        tabPanel("Gols Sofridos como Visitante",
                                 fluidRow(column(3, 
                                                 selectInput("Temporada301", 
                                                             strong("Selecione o Ano:"), 
                                                             choices=c("Todas Temporada"= "Todas Temporada",
                                                                       "2003"="2003",
                                                                       "2004"="2004",
                                                                       "2005"="2005",
                                                                       "2006"="2006",
                                                                       "2007"="2007",
                                                                       "2008"="2008",
                                                                       "2009"="2009",
                                                                       "2010"="2010",
                                                                       "2011"="2011",
                                                                       "2012"="2012",
                                                                       "2013"="2013",
                                                                       "2014"="2014",
                                                                       "2015"="2015",
                                                                       "2016"="2016",
                                                                       "2017"="2017",
                                                                       "2018"="2018",
                                                                       "2019"="2019",
                                                                       "2020"="2020"),
                                                             selected = "2020")),
                                          column(9,
                                                 plotlyOutput("plot301", height = 600))))
                        
                        
                      )# barra de navegacao interna
             ),# barra de navegacao superior (d2021 da Escola)            
             
             ######################## ABA JOGOS ############################
             
             tabPanel("Números de jogos",
                      tabsetPanel(
                        ##
                        tabPanel("Jogos disputados",
                                 fluidRow(column(9,
                                                 plotlyOutput("plot18", height = 600)))),
                        tabPanel("Jogos como Mandante",
                                 fluidRow(column(9,
                                                 plotlyOutput("plot19", height = 600)))),
                        tabPanel("Jogos como Visitante",
                                 fluidRow(column(9,
                                                 plotlyOutput("plot20", height = 600))))
                        
                        
                        
                      )# barra de navegacao interna
             ),# barra de navegacao superior (d2021 da Escola)  
             
             
             
             
             
             tabPanel("Sobre", icon = icon("comment", lib = "glyphicon"),
                      includeMarkdown("sobre.md"))
             
  )#navbarPage
)#fluidPage
)#shinyUI

